[project]
name = "directors-reimbursements"
version = "0.0.1"
description = "Create director's reimbursements for Phoenix Bridge Club"
authors = [
    {name = "Jeff Watkins", email = "jeffwatkins2000@gmail.com"}
]
readme = "README.md"
requires-python = '>=3.10'

include = [
    "HISTORY.md",
    "src/directors_reimbursements/images/*.png",
    "src/directors_reimbursements/images/*.ico",
    ]

dependencies = [
    "clipboard>=0.0.4",
    "dotenv>=0.9.9",
    "openpyxl>=3.1.5",
    "platformdirs>=4.12.2",
    "psiutils>=2.0.3",
    "python-dateutil>=2.9.0.post0",
]

[dependency-groups]
dev = ['pytest']

[build-system]
requires = ['uv-build']
build-backend = 'uv_build'


[tool.ruff]
line-length = 79
target-version = "py311"

[tool.ruff.lint]
select = ["E", "F", "I", "N", "W", "B", "UP"]

[tool.uv.sources]
psiutils = { path = "../../psi-utilities/psiutils", editable = true }
