"""Text strings."""

ELLIPSIS = ' ...'
ACCEPT = 'Accept'
DELETE_PROMPT = 'Are you sure you wish to delete this record?'
CLOSE = 'Close'
DELETE = 'Delete'
EDIT = 'Edit'
EXIT = 'Exit'
OPEN = 'Open'
HIDE = 'Hide'
NEW = 'New'
NO_SUCH_FILE = 'no such file or directory'
OK = 'OK'
CONFIG = 'Preferences'
QUIT = 'Quit'
SAVE = 'Save'
SELECT = 'Select'
SHOW = 'Show'
DIRECTORS = 'Director\'s'
TITLE = 'Director\'s Reimbursements'
PREVIOUS = 'Prev'
NEXT = 'Next'
